In [3]:
import pandas as pd 


file = pd.read_csv("../../data/raw/nomenclature.csv")

file.head()

,#,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,# Nomenclature for Solar system bodies,NaN,NaN,NaN,NaN,NaN,NaN
1,#,NaN,NaN,NaN,NaN,NaN,NaN
2,# Nomenclature data was obtained from the web ...,NaN,NaN,NaN,NaN,NaN,NaN
3,#,NaN,NaN,NaN,NaN,NaN,NaN
4,# One rule per line. Each rule contains seven ...,NaN,NaN,NaN,NaN,NaN,NaN