In [1]:
from scripts2 import project_functions
df = project_functions.load_and_process('../../data/raw/nomenclature.csv')
df.head()

,index,Planet Name,ID,FeatureName,FeatureType,Planetary Feature,Latitude of Center of Planetary Feature,Longitude of Center of Planetary Feature,Size of Planetary Feature(km)
0,1357,Mars,4574.0,Pandorae Fretum,albedo feature,AL,-24.741878,44.0,0.0
1,1459,Mars,6596.0,Xanthe,albedo feature,AL,9.884955,310.0,0.0
2,1168,Mars,2132.0,Gehon,albedo feature,AL,14.831743,360.0,0.0
3,1462,Mars,6639.0,Yaonis Regio,albedo feature,AL,-39.667248,40.0,0.0
4,1165,Mars,4213.0,Nereidum Fretum,albedo feature,AL,-44.661768,305.0,0.0